config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'

  resources :session, only: %i[new create destroy]
  resources :users

  resources :boards do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :users

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :board
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_and_belongs_to_many :tasks
  has_and_belongs_to_many :boards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
  end

  def show
    @board = Board.find(params[:id])
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)

    if @board.save
      redirect_to @board
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])

    if @board.update(board_params)
      redirect_to @board
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def board_params
    params.require(:board).permit(:title, :body)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new; end


  def create
    user_params = params.require(:session)
    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])

    if user.present?
      session[:user_id] = user.id
      redirect_to root_path, notice: 'You have entered the site'
    else
      flash.now[:alert] = 'Incorrect email or password'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'You have logged out of your account'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @board = Board.find(params[:board_id])
    @tasks = @board.tasks
  end

  def show
    @board = Board.find(params[:board_id])
    @task = @board.tasks.find(params[:id])
  end

  def new
    @board = Board.find(params[:board_id])
    @task = Task.new
    @users = User.all
  end

  def create
    @board = Board.find(params[:board_id])
    @task = @board.tasks.create(task_params)
    @user = User.find_by(nickname: task_params[:nickname])
    redirect_to board_path(@board)
  end

  def edit
    @board = Board.find(params[:board_id])
    @task = @board.tasks.find(params[:id])
    @users = User.all
  end

  def update
    @board = Board.find(params[:board_id])
    @task = @board.tasks.find(params[:id])

    if @task.update(task_params)
      redirect_to @board
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @board = Board.find(params[:board_id])
    @task = Board.find(params[:board_id]).tasks.find(params[:id])
    @task.destroy

    redirect_to @board, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title_task, :body, :status, :nickname)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:name, :nickname, :email, :password)
    User.create(user_params)
    redirect_to root_path, notice: 'You have successfully registered!'
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path, status: :see_other
  end

  def user_params
    params.require(:user).permit(:name, :nickname, :email, :password_digest)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/_form.html.erb
<%= form_with model: board do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% board.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-5">
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% board.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="flex w-28 p-1 border-2 mx-auto border-black rounded-md hover:bg-blue">
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Edit Board</h1>

<%= render "form", board: @board %>

app/views/boards/index.html.erb
<h1 class="flex p-2 px-10 font-black font-mono text-3xl">Boards</h1>
<div class="p-2 px-7 mb-5">
  <ul>
    <% @boards.each do |board| %>
      <li>
        <%= link_to board.title, board, class: "hover:underline hover:text-blue" %>
      </li>
    <% end %>
  </ul>
</div>
<div class="flex w-32 p-1 border-2 ml-3 border-black rounded-md hover:bg-blue">
  <%= link_to "Add new board", new_board_path %>
</div>

app/views/boards/new.html.erb
<div class="flex flex-col items-center pt-20">
  <h1 class="font-mono font-semibold text-2xl mb-5">Add New Board</h1>
  <%= render "form", board: @board %>
</div>

app/views/boards/show.html.erb
<div class="flex justify-between items-center font-mono mx-auto self-center px-10 mb-3">
  <%= link_to "Add new task", new_board_task_path(@board), class: "hover:underline" %>
  <div class="flex-col">
    <h1 class="text-3xl mb-2 font-bold"><%= @board.title %></h1>
    <p><%= @board.body %></p>
  </div>
  <ul>
    <li class="hover:underline"><%= link_to "Edit", edit_board_path(@board) %></li>
    <li class="hover:underline"><%= link_to "Destroy", board_path(@board), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    } %></li>
  </ul>
</div>
<hr class="mb-5">

<div class="p-6">
  <% @board.tasks.each do |task| %>
    <div class="flex justify-between border rounded font-mono mb-0.5">
      <h1 class="min-w-36 px-3 border-r"><%= task.title_task %></h1>
      <p class="w-1/2 border-r"><%= task.body %></p>
      <p class="w-36 border-r"><%= task.status %></p>
      <p class="w-36">person</p>
      <div class="bg-blue px-3 items-center">
        <%= link_to "Edit", edit_board_task_path(@board), class: "hover:underline" %>
        |
        <%= link_to "Destroy", board_task_path(@board), class: "hover:underline", data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                      } %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
  </head>

  <body>
    <div>
      <div class="flex justify-between p-5 bg-gray mb-5">
        <p class="text-orange text-6xl font-mono font-black mx-auto self-center pl-40 hover:underline"><%= link_to "MyTaskManager", root_path %></p>
        <div class="flex items-center place-items-end gap-2">
          <% if current_user.present? %>
            <%= link_to "@#{current_user.nickname}", user_path(current_user), class: "flex p-0.5 px-2 rounded-md bg-green" %>
            <%= button_to "Sign out", session_path(session), method: :delete, class: "flex p-1 border-2 border-black rounded-md hover:bg-blue" %>
          <% else %>
            <%= link_to "Registration", new_user_path, class: "flex p-1 border-2 border-black rounded-md bg-white hover:bg-blue" %>
            <%= link_to "Login", new_session_path, class: "flex p-1 border-2 border-black rounded-md bg-white hover:bg-blue" %>
          <% end %>
        </div>
      </div>

      <% if flash[:notice].present? %>
        <p><%= flash[:notice] %></p>
      <% elsif flash[:alert].present? %>
        <p><%= flash[:alert] %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/session/create.html.erb
<h1>Sessions#create</h1>
<p>Find me in app/views/sessions/create.html.erb</p>

app/views/session/new.html.erb
<div class="container">
  <h2 class="title">Login</h2>
  <p>Enter your email and password to log in to the site</p>

  <div>
    <%= form_with scope: :session, url: session_index_path, data: {turbo: false} do |form| %>
      <p><%= form.label :email %></p>
      <p><%= form.text_field :email, class: '' %></p>

      <p><%= form.label :password %></p>
      <p><%= form.password_field :password, class: '' %></p>
      
      <p><%= form.submit 'Sign in', class: ''%></p>
    <% end %>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with model: [@board, @task] do |form| %>
  <p>
    <%= form.label :title_task %><br>
    <%= form.text_field :title_task %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p class="mb-5">
    <%= form.label :status %><br>
    <%= form.select :status, ["In Dev", "QA", "Done"] %>
  </p>
  </p>
  <p class="mb-5">
    <%= form.label :nickname %><br>
    <%= form.select :nickname, [@users.map { |user| user.nickname }] %>
  </p>
  <p class="flex w-28 p-1 border-2 mx-auto border-black rounded-md hover:bg-blue">
    <%= form.submit %>
  </p>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Tasks</h1>

<%= render "form", task: @task %>

app/views/tasks/new.html.erb
<div class="flex flex-col items-center pt-20">
  <h1 class="font-mono font-semibold text-2xl mb-5">Add New Tasks</h1>
  <%= render "form", task: @task %>
</div>

app/views/tasks/show.html.erb
<h1><%= @task.title_task %></h1>

<p><%= @task.body %></p>
<p><%= @task.status %></p>

<ul>
  <li><%= link_to "Edit", edit_board_task_path(@board) %></li>

  <li><%= link_to "Destroy", board_task_path(@board), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="container">
  <h2 class="title">Edit</h2>

  <div>
    <%= form_with model: @user do |form| %>
      <p><%= form.label :name, 'Your name' %></p>
      <p><%= form.text_field :name, class: '' %></p>

      <p><%= form.label :nickname, 'Your nickname' %></p>
      <p><%= form.text_field :nickname, class: '' %></p>

      <p><%= form.label :email %></p>
      <p><%= form.text_field :email, class: '' %></p>
      
      <p><%= form.label :password %></p>
      <p><%= form.password_field :password, class: '' %></p>

      <p><%= form.submit 'Edit', class: ''%></p>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h2 class="title">Join us</h2>

  <div>
    <%= form_with model: @user do |form| %>
      <p><%= form.label :name, 'Your name' %></p>
      <p><%= form.text_field :name, class: '' %></p>

      <p><%= form.label :nickname, 'Your nickname' %></p>
      <p><%= form.text_field :nickname, class: '' %></p>

      <p><%= form.label :email %></p>
      <p><%= form.text_field :email, class: '' %></p>
      
      <p><%= form.label :password %></p>
      <p><%= form.password_field :password, class: '' %></p>

      <p><%= form.submit 'Register', class: ''%></p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="flex-col">
  <h1 class="text-3xl mb-2 font-bold"><%= @user.nickname %></h1>
  <p><%= @user.name %></p>
  <p><%= @user.email %></p>
</div>
<ul>
  <li class="hover:underline"><%= link_to "Edit", edit_user_path(@user) %></li>
  <li class="hover:underline"><%= link_to "Destroy", user_path(@user), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>